### ISSUE TITLE
全部设置好了 错误问题 

### ISSUE THREAD

**Issue by izhuolin** [gaohan-cmd/mt#1]
未设置MT论坛账号密码

全部按照要求弄了 服务器也重启三四遍也还是显示这个 变量环境也设置了 都设置好了 求解

**Comment by gaohan-cmd** [comment]
请可以jian

> 未设置MT论坛账号密码
> 
> 全部按照要求弄了 服务器也重启三四遍也还是显示这个 变量环境也设置了 都设置好了 求解

可以检查一下环境变量名是否是这个 mtluntan
然后格式是符合这样的 Han&h1234

如果上述操作还未成功 那么可以考虑直接修改源代码，将
username, password = mtluntan.split('&')替换成
username = ‘账号’
password = ‘密码’

![image](https://github.com/gaohan-cmd/mt/assets/63499259/fe5ddb44-0b5b-4d96-a8ec-8f5b7b766b3a)

**Comment by izhuolin** [comment]
> 请可以jian
> 
> > 未设置MT论坛账号密码
> > 全部按照要求弄了 服务器也重启三四遍也还是显示这个 变量环境也设置了 都设置好了 求解
> 
> 可以检查一下环境变量名是否是这个 mtluntan 然后格式是符合这样的 Han&h1234
> 
> 如果上述操作还未成功 那么可以考虑直接修改源代码，将 username, password = mtluntan.split('&')替换成 username = ‘账号’ password = ‘密码’
> 
> ![image](https://private-user-images.githubusercontent.com/63499259/310061120-fe5ddb44-0b5b-4d96-a8ec-8f5b7b766b3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzIxMzAsIm5iZiI6MTcwOTYzMTgzMCwicGF0aCI6Ii82MzQ5OTI1OS8zMTAwNjExMjAtZmU1ZGRiNDQtMGI1Yi00ZDk2LWE4ZWMtOGY1YjdiNzY2YjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA5NDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YzUwMjU0MmM2NjE1ZTQzODdjMWNlMGQ4NmZhYmRmNTYzM2U0YzkxNGJkYzQ3MDFkMGRkZTI0ZjdmZWIwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zNxfF9VpRcTDM1Utrzp2VMdZiJReIiAfAR2FPP7I3KY)

我使用的上第二种替换方式 现在出现新的问题 第一种变量环境还是无用
![IMG_9336](https://github.com/gaohan-cmd/mt/assets/61179498/e4190072-f343-497b-a67e-15c8a7452f71)

**Comment by izhuolin** [comment]
源代码这样修改了 执行结果还是如此 其实账号密码再官网可以正常登入
![IMG_9337](https://github.com/gaohan-cmd/mt/assets/61179498/226f909e-9729-4a7e-aabc-1870786dd0d6)
![IMG_9338](https://github.com/gaohan-cmd/mt/assets/61179498/89be47e9-5242-464f-a68c-32822e9c1f14)

**Comment by gaohan-cmd** [comment]
> > 请可以jian
> > > 未设置MT论坛账号密码
> > > 全部按照要求弄了 服务器也重启三四遍也还是显示这个 变量环境也设置了 都设置好了 求解
> > 
> > 
> > 可以检查一下环境变量名是否是这个 mtluntan 然后格式是符合这样的 Han&h1234
> > 如果上述操作还未成功 那么可以考虑直接修改源代码，将 username, password = mtluntan.split('&')替换成 username = ‘账号’ password = ‘密码’
> > ![image](https://private-user-images.githubusercontent.com/63499259/310061120-fe5ddb44-0b5b-4d96-a8ec-8f5b7b766b3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzIxMzAsIm5iZiI6MTcwOTYzMTgzMCwicGF0aCI6Ii82MzQ5OTI1OS8zMTAwNjExMjAtZmU1ZGRiNDQtMGI1Yi00ZDk2LWE4ZWMtOGY1YjdiNzY2YjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA5NDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YzUwMjU0MmM2NjE1ZTQzODdjMWNlMGQ4NmZhYmRmNTYzM2U0YzkxNGJkYzQ3MDFkMGRkZTI0ZjdmZWIwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zNxfF9VpRcTDM1Utrzp2VMdZiJReIiAfAR2FPP7I3KY)
> 
> 我使用的上第二种替换方式 现在出现新的问题 第一种变量环境还是无用 ![IMG_9336](https://private-user-images.githubusercontent.com/61179498/310066395-e4190072-f343-497b-a67e-15c8a7452f71.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzQ4ODUsIm5iZiI6MTcwOTYzNDU4NSwicGF0aCI6Ii82MTE3OTQ5OC8zMTAwNjYzOTUtZTQxOTAwNzItZjM0My00OTdiLWE2N2UtMTVjOGE3NDUyZjcxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMDI5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDdlMDBkZWRjNjUwZWJkOTJmZGU4YzYyZTg1ZDNlZjBlYjIzMjczNWM1ODkxYWQ0YWNhMzhkNzkyYzhlOWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9PXiO8VRijv7bOhlfCTxRiLO8YTChU-UCKnTaC2S-zc)

把这部分改成这样
# 从环境变量中读取账号密码
mtluntan = os.getenv("mtluntan")
if mtluntan is not None:
    username, password = mtluntan.split('&')
    main(username,password)
else:
    print('未设置MT论坛账号密码')
    
==================================
# 从环境变量中读取账号密码
mtluntan = “zhuolin&123456”
if mtluntan is not None:
    username, password = mtluntan.split('&')
    main(username,password)
else:
    print('未设置MT论坛账号密码')

**Comment by izhuolin** [comment]
已改成那样但是还是无法运行
![IMG_9339](https://github.com/gaohan-cmd/mt/assets/61179498/1c0d9bd9-0f50-47e8-bf01-abe8dccf8415)

**Comment by gaohan-cmd** [comment]
> 已改成那样但是还是无法运行 ![IMG_9339](https://private-user-images.githubusercontent.com/61179498/310083051-1c0d9bd9-0f50-47e8-bf01-abe8dccf8415.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzUzNTYsIm5iZiI6MTcwOTYzNTA1NiwicGF0aCI6Ii82MTE3OTQ5OC8zMTAwODMwNTEtMWMwZDliZDktMGY1MC00N2U4LWJmMDEtYWJlOGRjY2Y4NDE1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMDM3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzVkZmZiM2Q5M2ZhODhhMTBlNzUyNzA0MWQzYjEyNTFkZTcyYmMyOWIzZTYxMDRjNWI0NWRmYmFjNmI4MDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dqZEbu9MMcSBt9wlv-pK1cSQLHpyE7LoRdnbXfY_JPg)
好像是我记错语法了😂 改成这个吧，再不行的话就只要
    username, password = mtluntan.split('&')
    main(username,password) 这两行其余都删掉
    
# 从环境变量中读取账号密码
mtluntan = 'zhuolin’
if mtluntan is not None:
    username, password = mtluntan.split('&')
    main(username,password)
else:
    print('未设置MT论坛账号密码')

**Comment by gaohan-cmd** [comment]
> > 已改成那样但是还是无法运行 ![IMG_9339](https://private-user-images.githubusercontent.com/61179498/310083051-1c0d9bd9-0f50-47e8-bf01-abe8dccf8415.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzUzNTYsIm5iZiI6MTcwOTYzNTA1NiwicGF0aCI6Ii82MTE3OTQ5OC8zMTAwODMwNTEtMWMwZDliZDktMGY1MC00N2U4LWJmMDEtYWJlOGRjY2Y4NDE1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMDM3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzVkZmZiM2Q5M2ZhODhhMTBlNzUyNzA0MWQzYjEyNTFkZTcyYmMyOWIzZTYxMDRjNWI0NWRmYmFjNmI4MDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dqZEbu9MMcSBt9wlv-pK1cSQLHpyE7LoRdnbXfY_JPg)
> > 好像是我记错语法了😂 改成这个吧，再不行的话就只要
> > username, password = mtluntan.split('&')
> > main(username,password) 这两行其余都删掉
> 
> # 从环境变量中读取账号密码
> mtluntan = 'zhuolin’ if mtluntan is not None: username, password = mtluntan.split('&') main(username,password) else: print('未设置MT论坛账号密码')

注意缩进格式不要变化，只改字母

**Comment by izhuolin** [comment]
> > > 已改成那样但是还是无法运行 ![IMG_9339](https://private-user-images.githubusercontent.com/61179498/310083051-1c0d9bd9-0f50-47e8-bf01-abe8dccf8415.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzUzNTYsIm5iZiI6MTcwOTYzNTA1NiwicGF0aCI6Ii82MTE3OTQ5OC8zMTAwODMwNTEtMWMwZDliZDktMGY1MC00N2U4LWJmMDEtYWJlOGRjY2Y4NDE1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMDM3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzVkZmZiM2Q5M2ZhODhhMTBlNzUyNzA0MWQzYjEyNTFkZTcyYmMyOWIzZTYxMDRjNWI0NWRmYmFjNmI4MDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dqZEbu9MMcSBt9wlv-pK1cSQLHpyE7LoRdnbXfY_JPg)
> > > 好像是我记错语法了😂 改成这个吧，再不行的话就只要
> > > username, password = mtluntan.split('&')
> > > main(username,password) 这两行其余都删掉
> > 
> > 
> > # 从环境变量中读取账号密码
> > mtluntan = 'zhuolin’ if mtluntan is not None: username, password = mtluntan.split('&') main(username,password) else: print('未设置MT论坛账号密码')
> 
> 注意缩进格式不要变化，只改字母

不搞了 不搞了 我第一次觉得这语言比娘们好多事 虽然没怎么接触过 但是它是真屁事多！一下缩近一下语句
